name: Renew XNAT Tokens

on:
  workflow_dispatch:
      inputs:
        xrelay_host:
          description: 'XNAT Relay Hostname'
          required: true
          default: "https://xrelay.bnc.brown.edu"
        xrelay_user:
          description: 'XNAT Relay Username'
          required: true
          default: ${{ secrets.XNAT_RELAY_USER }}
        xrelay_pass: 
          description: 'XNAT Relay Password'
          required: true
          default: ${{ secrets.XNAT_RELAY_PASS }}
        xserver_host: 
          description: 'XNAT Server Hostname'
          required: true
          default: "https://xnat.bnc.brown.edu"
        xserver_user:
          description: 'XNAT Server Username'
          required: true
          default: ${{ secrets.XNAT_SERVER_USER }}
        xserver_pass:
          description: 'XNAT Server Password'
          required: true
          default:  ${{ secrets.XNAT_SERVER_PASS }}

jobs:
  renew_tokens:
    name: Run renew_xnat_tokens Python Script
    runs-on: self-hosted
    container:
      image: ghcr.io/xnat-admin-tools:latest

    steps: 
      - name: Run renew_xnat_tokens  
        run: 
              renew_xnat_tokens \
                "${{ inputs.xrelay_host }}" \
                "${{ inputs.xrelay_user }}" \
                "${{ inputs.xrelay_pass }}" \
                "${{ inputs.xserver_host }}" \
                "${{ inputs.xserver_user }}" \
                "${{ inputs.xserver_pass }}"
