name: Renew XNAT Tokens

on:
  workflow_dispatch:
      inputs:
        arguments:
          xrelay_host: "https://xrelay.bnc.brown.edu"
          xrelay_user: ${{ secrets.XNAT_RELAY_USER }}
          xrelay_pass: ${{ secrets.XNAT_RELAY_PASS }}
          xserver_host: "https://xnat.bnc.brown.edu"
          xserver_user: ${{ secrets.XNAT_SERVER_USER }}
          xserver_pass: ${{ secrets.XNAT_SERVER_PASS }}

jobs:
  renew_tokens:
    name: Run renew_xnat_tokens Python Script
    runs-on: self-hosted
    container:
      image: ghcr.io/xnat-admin-tools:latest

    steps: 
      - name: Run renew_xnat_tokens  
        run: 
          renew_xnat_tokens ${{ inputs.arguments }}
