name: Renew XNAT Tokens

on:
  workflow_dispatch:
      inputs:
        xrelay_host:
          description: 'XNAT Relay Hostname'
          required: true
          default: "https://xrelay.bnc.brown.edu"
        xserver_host: 
          description: 'XNAT Server Hostname'
          required: true
          default: "https://xnat.bnc.brown.edu"
          
env:
  XRELAY_HOST: ${{ github.event.inputs.xrelay_host }}
  XRELAY_USER: ${{ secrets.XNAT_RELAY_USER }}
  XRELAY_PASS: ${{ secrets.XNAT_RELAY_PASS }}
  XSERVER_HOST: ${{ github.event.inputs.xserver_host }}
  XSERVER_USER: ${{ secrets.XNAT_SERVER_USER }}
  XSERVER_PASS: ${{ secrets.XNAT_SERVER_PASS }}

jobs:
  renew_tokens:
    name: Run renew_xnat_tokens Python Script
    runs-on: self-hosted
    container:
      image: ghcr.io/brown-bnc/xnat-admin-tools:latest

    steps: 
      - name: Run renew_xnat_tokens  
        run: |
          xnat-renew-xnat-tokens  \
                "$XRELAY_HOST" \
                "$XRELAY_USER" \
                "$XRELAY_PASS" \
                "$XSERVER_HOST" \
                "$XSERVER_USER" \
                "$XSERVER_PASS"
